Default: &defaults
  user: Chernobog
  password: Chernobog
  host: localhost
  port: 27017
  database: Chernobog
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Chernobog_test
  <<: *defaults

Staging:
  database: Chernobog_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Chernobog_production
  poolsize: 100
  <<: *defaults
