Default: &defaults
  user: Yosog
  password: Yosog
  host: localhost
  port: 27017
  database: Yosog
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Yosog_test
  <<: *defaults

Staging:
  database: Yosog_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Yosog_production
  poolsize: 100
  <<: *defaults
